export const ADD_ISSUE_ALTERNATIVE = 'ADD_ISSUE_ALTERNATIVE';
export const CLEAR_ALTERNATIVE_TEXT = 'CLEAR_ALTERNATIVE_TEXT';
export const REMOVE_ISSUE_ALTERNATIVE = 'REMOVE_ISSUE_ALTERNATIVE';
export const SET_ALTERNATIVE_TEXT = 'SET_ALTERNATIVE_TEXT';
export const SET_QUESTION_TYPE = 'SET_QUESTION_TYPE';
export const SET_RESOLUTION_TYPE = 'SET_RESOLUTION_TYPE';
export const UPDATE_ALTERNATIVE_TEXT = 'UPDATE_ALTERNATIVE_TEXT';
export const UPDATE_ISSUE_SETTING = 'UPDATE_ISSUE_SETTING';
