export const DISABLE_VOTING = 'DISABLE_VOTING';
export const ENABLE_VOTING = 'ENABLE_VOTING';
export const RECEIVE_VOTE = 'ADD_VOTE';
export const SUBMIT_ANONYMOUS_VOTE = 'server/SUBMIT_ANONYMOUS_VOTE';
export const SUBMIT_REGULAR_VOTE = 'server/SUBMIT_REGULAR_VOTE';
