
FROM node:8.5-alpine

ENV APP_DIR=/srv/app
ENV PRODUCTION=true
ENV NODE_ENV=production

RUN mkdir -p $APP_DIR
WORKDIR $APP_DIR

RUN apk --no-cache --update add git

COPY package.json yarn.lock $APP_DIR/
RUN yarn

COPY . .
RUN yarn build:prod

EXPOSE 3000

CMD ["yarn", "prod"]