
FROM node:7.9-alpine

ENV APP_DIR=/srv/app
ENV PRODUCTION=true

RUN mkdir -p $APP_DIR
WORKDIR $APP_DIR

RUN apk --no-cache --update add git

COPY package.json .
RUN npm install

COPY . .
RUN npm run build:prod

EXPOSE 3000

CMD ["npm","run","prod"]