module.exports = {
  ADMIN_CREATE_ISSUE: 'server/ADMIN_CREATE_ISSUE',
  ADMIN_CLOSE_ISSUE: 'server/ADMIN_CLOSE_ISSUE',
  ADMIN_DELETE_ISSUE: 'server/ADMIN_DELETE_ISSUE',
  TOGGLE_REGISTRATION: 'TOGGLE_REGISTRATION',
};
