module.exports = {
  AUTH_SIGNED_IN: 'AUTH_SIGNED_IN',
  AUTH_SIGN_OUT: 'server/AUTH_SIGN_OUT',
  AUTH_SIGNED_OUT: 'AUTH_SIGNED_OUT',
  AUTH_REGISTER: 'server/AUTH_REGISTER',
  AUTH_REGISTERED: 'AUTH_REGISTERED',
  ADMIN_CREATE_GENFORS: 'server/ADMIN_CREATE_GENFORS',
  ADMIN_LOGIN: 'server/ADMIN_LOGIN',
};
