module.exports = {
  CLOSE_ISSUE: 'CLOSE_ISSUE',
  OPEN_ISSUE: 'OPEN_ISSUE',
  DELETED_ISSUE: 'DELETED_ISSUE',
  SEND_VOTE: 'SEND_VOTE',
  VOTING_NOT_STARTED: 'VOTING_NOT_STARTED',
  VOTING_IN_PROGRESS: 'VOTING_IN_PROGRESS',
  VOTING_FINISHED: 'VOTING_FINISHED',
};
