module.exports = {
  ADMIN_END_MEETING: 'server/CLOSE_MEETING',
  END_MEETING: 'END_MEETING',
  OPEN_MEETING: 'OPEN_MEETING',
  TOGGLE_REGISTRATION_STATE: 'server/TOGGLE_REGISTRATION_STATE',
  TOGGLED_REGISTRATION_STATE: 'TOGGLED_REGISTRATION_STATE',
};
