module.exports = {
  ADD_USER: 'ADD_USER',
  TOGGLE_CAN_VOTE: 'TOGGLE_CAN_VOTE',
  ADMIN_TOGGLE_CAN_VOTE: 'server/TOGGLE_CAN_VOTE',
  REQUEST_USER_LIST: 'server/REQUEST_USER_LIST',
  RECEIVE_USER_LIST: 'USER_LIST',
};
