name: Lint and test

on: [push]

jobs:
  check:
    name: Lint and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '8.x'
    - name: Cache Node.js modules
      uses: actions/cache@v2
      with:
        path: ~/.npm 
        key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-node-
          ${{ runner.OS }}-
    - name: Install dependencies
      run: yarn
    - name: Test
      run: yarn test
    - name: Lint
      run: yarn lint
    - name: Build
      run: yarn build:prod